name: Deploy InVEST Download Link Updater

on:
    push:
        branches:
            - main

jobs:

    deploy-latest:
        name: "Deploy Gcloud Function"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up GCP
              # Secrets not available in PR so don't use GCP.
              # We only want to deploy function in a release.
              if: github.event_name != 'pull_request'
              uses: google-github-actions/setup-gcloud@v0
              with:
                  project_id: ${{ secrets.GCP_PROJECT_ID }}
                  service_account_key: ${{ secrets.GOOGLE_SERVICE_ACC_KEY }}

            - run: gcloud functions deploy investDownloadLinks --source="./app" --runtime nodejs12 --trigger-http --allow-unauthenticated
